#include <iostream>
#include <unistd.h>
#include <sstream>
#include "bus.hpp"

#include "display/text_40x24.hpp"
#include "devices/keyboard.hpp"

/**
 * Process read and write to simulated IO bus for peripherals 
 * All external bus accesses are 8-bit data, 16-bit address.
 * So that is the interface here.
 *
 * */

// Function pointer type for memory bus handlers
typedef uint8_t (*memory_read_handler)(uint16_t);
typedef void (*memory_write_handler)(uint16_t, uint8_t);

// Table of memory read handlers
memory_read_handler C0xx_memory_read_handlers[] = {
    /* 0xC000 */ kb_memory_read,    // Keyboard latch read
    /* 0xC001 */ nullptr,            // unused,
    /* 0xC002 */ nullptr,            // unused,
    /* 0xC003 */ nullptr,            // unused,
    /* 0xC004 */ nullptr,            // unused,
    /* 0xC005 */ nullptr,            // unused,
    /* 0xC006 */ nullptr,            // unused,
    /* 0xC007 */ nullptr,            // unused,
    /* 0xC008 */ nullptr,            // unused,
    /* 0xC009 */ nullptr,            // unused,
    /* 0xC00A */ nullptr,            // unused,
    /* 0xC00B */ nullptr,            // unused,
    /* 0xC00C */ nullptr,            // unused,
    /* 0xC00D */ nullptr,            // unused,
    /* 0xC00E */ nullptr,            // unused,
    /* 0xC00F */ nullptr,            // unused,
    /* 0xC010 */ kb_memory_read,     // unused,
    /* 0xC011 */ nullptr,            // unused,
    /* 0xC012 */ nullptr,            // unused,
    /* 0xC013 */ nullptr,            // unused,
    /* 0xC014 */ nullptr,            // unused,
    /* 0xC015 */ nullptr,            // unused,
    /* 0xC016 */ nullptr,            // unused,
    /* 0xC017 */ nullptr,            // unused,
    /* 0xC018 */ nullptr,            // unused,
    /* 0xC019 */ nullptr,            // unused,
    /* 0xC01A */ nullptr,            // unused,
    /* 0xC01B */ nullptr,            // unused,
    /* 0xC01C */ nullptr,            // unused,
    /* 0xC01D */ nullptr,            // unused,
    /* 0xC01E */ nullptr,            // unused,
    /* 0xC01F */ nullptr,            // unused,
    /* 0xC020 */ nullptr,            // unused,
    /* 0xC021 */ nullptr,            // unused,
    /* 0xC022 */ nullptr,            // unused,
    /* 0xC023 */ nullptr,            // unused,
    /* 0xC024 */ nullptr,            // unused,
    /* 0xC025 */ nullptr,            // unused,
    /* 0xC026 */ nullptr,            // unused,
    /* 0xC027 */ nullptr,            // unused,
    /* 0xC028 */ nullptr,            // unused,
    /* 0xC029 */ nullptr,            // unused,
    /* 0xC02A */ nullptr,            // unused,
    /* 0xC02B */ nullptr,            // unused,
    /* 0xC02C */ nullptr,            // unused,
    /* 0xC02D */ nullptr,            // unused,
    /* 0xC02E */ nullptr,            // unused,
    /* 0xC02F */ nullptr,            // unused,
    /* 0xC030 */ nullptr,            // unused,
    /* 0xC031 */ nullptr,            // unused,
    /* 0xC032 */ nullptr,            // unused,
    /* 0xC033 */ nullptr,            // unused,
    /* 0xC034 */ nullptr,            // unused,
    /* 0xC035 */ nullptr,            // unused,
    /* 0xC036 */ nullptr,            // unused,
    /* 0xC037 */ nullptr,            // unused,
    /* 0xC038 */ nullptr,            // unused,
    /* 0xC039 */ nullptr,            // unused,
    /* 0xC03A */ nullptr,            // unused,
    /* 0xC03B */ nullptr,            // unused,
    /* 0xC03C */ nullptr,            // unused,
    /* 0xC03D */ nullptr,            // unused,
    /* 0xC03E */ nullptr,            // unused,
    /* 0xC03F */ nullptr,            // unused,
    /* 0xC040 */ nullptr,            // unused,
    /* 0xC041 */ nullptr,            // unused,
    /* 0xC042 */ nullptr,            // unused,
    /* 0xC043 */ nullptr,            // unused,
    /* 0xC044 */ nullptr,            // unused,
    /* 0xC045 */ nullptr,            // unused,
    /* 0xC046 */ nullptr,            // unused,
    /* 0xC047 */ nullptr,            // unused,
    /* 0xC048 */ nullptr,            // unused,
    /* 0xC049 */ nullptr,            // unused,
    /* 0xC04A */ nullptr,            // unused,
    /* 0xC04B */ nullptr,            // unused,
    /* 0xC04C */ nullptr,            // unused,
    /* 0xC04D */ nullptr,            // unused,
    /* 0xC04E */ nullptr,            // unused,
    /* 0xC04F */ nullptr,            // unused,
    /* 0xC050 */ nullptr,            // unused,
    /* 0xC051 */ nullptr,            // unused,
    /* 0xC052 */ nullptr,            // unused,
    /* 0xC053 */ nullptr,            // unused,
    /* 0xC054 */ nullptr,            // unused,
    /* 0xC055 */ nullptr,            // unused,
    /* 0xC056 */ nullptr,            // unused,
    /* 0xC057 */ nullptr,            // unused,
    /* 0xC058 */ nullptr,            // unused,
    /* 0xC059 */ nullptr,            // unused,
    /* 0xC05A */ nullptr,            // unused,
    /* 0xC05B */ nullptr,            // unused,
    /* 0xC05C */ nullptr,            // unused,
    /* 0xC05D */ nullptr,            // unused,
    /* 0xC05E */ nullptr,            // unused,
    /* 0xC05F */ nullptr,            // unused,
    /* 0xC060 */ nullptr,            // unused,
    /* 0xC061 */ nullptr,            // unused,
    /* 0xC062 */ nullptr,            // unused,
    /* 0xC063 */ nullptr,            // unused,
    /* 0xC064 */ nullptr,            // unused,
    /* 0xC065 */ nullptr,            // unused,
    /* 0xC066 */ nullptr,            // unused,
    /* 0xC067 */ nullptr,            // unused,
    /* 0xC068 */ nullptr,            // unused,
    /* 0xC069 */ nullptr,            // unused,
    /* 0xC06A */ nullptr,            // unused,
    /* 0xC06B */ nullptr,            // unused,
    /* 0xC06C */ nullptr,            // unused,
    /* 0xC06D */ nullptr,            // unused,
    /* 0xC06E */ nullptr,            // unused,
    /* 0xC06F */ nullptr,            // unused,
    /* 0xC070 */ nullptr,            // unused,
    /* 0xC071 */ nullptr,            // unused,
    /* 0xC072 */ nullptr,            // unused,
    /* 0xC073 */ nullptr,            // unused,
    /* 0xC074 */ nullptr,            // unused,
    /* 0xC075 */ nullptr,            // unused,
    /* 0xC076 */ nullptr,            // unused,
    /* 0xC077 */ nullptr,            // unused,
    /* 0xC078 */ nullptr,            // unused,
    /* 0xC079 */ nullptr,            // unused,
    /* 0xC07A */ nullptr,            // unused,
    /* 0xC07B */ nullptr,            // unused,
    /* 0xC07C */ nullptr,            // unused,
    /* 0xC07D */ nullptr,            // unused,
    /* 0xC07E */ nullptr,            // unused,
    /* 0xC07F */ nullptr,            // unused,
};

memory_write_handler C0xx_memory_write_handlers[] = {
    /* 0xC000 */ kb_memory_write,    // Keyboard latch read
    /* 0xC001 */ nullptr,            // unused,
    /* 0xC002 */ nullptr,            // unused,
    /* 0xC003 */ nullptr,            // unused,
    /* 0xC004 */ nullptr,            // unused,
    /* 0xC005 */ nullptr,            // unused,
    /* 0xC006 */ nullptr,            // unused,
    /* 0xC007 */ nullptr,            // unused,
    /* 0xC008 */ nullptr,            // unused,
    /* 0xC009 */ nullptr,            // unused,
    /* 0xC00A */ nullptr,            // unused,
    /* 0xC00B */ nullptr,            // unused,
    /* 0xC00C */ nullptr,            // unused,
    /* 0xC00D */ nullptr,            // unused,
    /* 0xC00E */ nullptr,            // unused,
    /* 0xC00F */ nullptr,            // unused,
    /* 0xC010 */ kb_memory_write,     // unused,
    /* 0xC011 */ nullptr,            // unused,
    /* 0xC012 */ nullptr,            // unused,
    /* 0xC013 */ nullptr,            // unused,
    /* 0xC014 */ nullptr,            // unused,
    /* 0xC015 */ nullptr,            // unused,
    /* 0xC016 */ nullptr,            // unused,
    /* 0xC017 */ nullptr,            // unused,
    /* 0xC018 */ nullptr,            // unused,
    /* 0xC019 */ nullptr,            // unused,
    /* 0xC01A */ nullptr,            // unused,
    /* 0xC01B */ nullptr,            // unused,
    /* 0xC01C */ nullptr,            // unused,
    /* 0xC01D */ nullptr,            // unused,
    /* 0xC01E */ nullptr,            // unused,
    /* 0xC01F */ nullptr,            // unused,
    /* 0xC020 */ nullptr,            // unused,
    /* 0xC021 */ nullptr,            // unused,
    /* 0xC022 */ nullptr,            // unused,
    /* 0xC023 */ nullptr,            // unused,
    /* 0xC024 */ nullptr,            // unused,
    /* 0xC025 */ nullptr,            // unused,
    /* 0xC026 */ nullptr,            // unused,
    /* 0xC027 */ nullptr,            // unused,
    /* 0xC028 */ nullptr,            // unused,
    /* 0xC029 */ nullptr,            // unused,
    /* 0xC02A */ nullptr,            // unused,
    /* 0xC02B */ nullptr,            // unused,
    /* 0xC02C */ nullptr,            // unused,
    /* 0xC02D */ nullptr,            // unused,
    /* 0xC02E */ nullptr,            // unused,
    /* 0xC02F */ nullptr,            // unused,
    /* 0xC030 */ nullptr,            // unused,
    /* 0xC031 */ nullptr,            // unused,
    /* 0xC032 */ nullptr,            // unused,
    /* 0xC033 */ nullptr,            // unused,
    /* 0xC034 */ nullptr,            // unused,
    /* 0xC035 */ nullptr,            // unused,
    /* 0xC036 */ nullptr,            // unused,
    /* 0xC037 */ nullptr,            // unused,
    /* 0xC038 */ nullptr,            // unused,
    /* 0xC039 */ nullptr,            // unused,
    /* 0xC03A */ nullptr,            // unused,
    /* 0xC03B */ nullptr,            // unused,
    /* 0xC03C */ nullptr,            // unused,
    /* 0xC03D */ nullptr,            // unused,
    /* 0xC03E */ nullptr,            // unused,
    /* 0xC03F */ nullptr,            // unused,
    /* 0xC040 */ nullptr,            // unused,
    /* 0xC041 */ nullptr,            // unused,
    /* 0xC042 */ nullptr,            // unused,
    /* 0xC043 */ nullptr,            // unused,
    /* 0xC044 */ nullptr,            // unused,
    /* 0xC045 */ nullptr,            // unused,
    /* 0xC046 */ nullptr,            // unused,
    /* 0xC047 */ nullptr,            // unused,
    /* 0xC048 */ nullptr,            // unused,
    /* 0xC049 */ nullptr,            // unused,
    /* 0xC04A */ nullptr,            // unused,
    /* 0xC04B */ nullptr,            // unused,
    /* 0xC04C */ nullptr,            // unused,
    /* 0xC04D */ nullptr,            // unused,
    /* 0xC04E */ nullptr,            // unused,
    /* 0xC04F */ nullptr,            // unused,
    /* 0xC050 */ nullptr,            // unused,
    /* 0xC051 */ nullptr,            // unused,
    /* 0xC052 */ nullptr,            // unused,
    /* 0xC053 */ nullptr,            // unused,
    /* 0xC054 */ nullptr,            // unused,
    /* 0xC055 */ nullptr,            // unused,
    /* 0xC056 */ nullptr,            // unused,
    /* 0xC057 */ nullptr,            // unused,
    /* 0xC058 */ nullptr,            // unused,
    /* 0xC059 */ nullptr,            // unused,
    /* 0xC05A */ nullptr,            // unused,
    /* 0xC05B */ nullptr,            // unused,
    /* 0xC05C */ nullptr,            // unused,
    /* 0xC05D */ nullptr,            // unused,
    /* 0xC05E */ nullptr,            // unused,
    /* 0xC05F */ nullptr,            // unused,
    /* 0xC060 */ nullptr,            // unused,
    /* 0xC061 */ nullptr,            // unused,
    /* 0xC062 */ nullptr,            // unused,
    /* 0xC063 */ nullptr,            // unused,
    /* 0xC064 */ nullptr,            // unused,
    /* 0xC065 */ nullptr,            // unused,
    /* 0xC066 */ nullptr,            // unused,
    /* 0xC067 */ nullptr,            // unused,
    /* 0xC068 */ nullptr,            // unused,
    /* 0xC069 */ nullptr,            // unused,
    /* 0xC06A */ nullptr,            // unused,
    /* 0xC06B */ nullptr,            // unused,
    /* 0xC06C */ nullptr,            // unused,
    /* 0xC06D */ nullptr,            // unused,
    /* 0xC06E */ nullptr,            // unused,
    /* 0xC06F */ nullptr,            // unused,
    /* 0xC070 */ nullptr,            // unused,
    /* 0xC071 */ nullptr,            // unused,
    /* 0xC072 */ nullptr,            // unused,
    /* 0xC073 */ nullptr,            // unused,
    /* 0xC074 */ nullptr,            // unused,
    /* 0xC075 */ nullptr,            // unused,
    /* 0xC076 */ nullptr,            // unused,
    /* 0xC077 */ nullptr,            // unused,
    /* 0xC078 */ nullptr,            // unused,
    /* 0xC079 */ nullptr,            // unused,
    /* 0xC07A */ nullptr,            // unused,
    /* 0xC07B */ nullptr,            // unused,
    /* 0xC07C */ nullptr,            // unused,
    /* 0xC07D */ nullptr,            // unused,
    /* 0xC07E */ nullptr,            // unused,
    /* 0xC07F */ nullptr,            // unused,
};

uint8_t memory_bus_read(uint16_t address) {
    if (address >= 0xC000 && address <= 0xC07F) {
        memory_read_handler funcptr =  C0xx_memory_read_handlers[address - 0xC000];
        if (funcptr != nullptr) {
            return (*funcptr)(address);
        } else return 0xEE;
    }
    return 0xEE; /* TODO: should return a random value 'floating bus'*/
}

void memory_bus_write(uint16_t address, uint8_t value) {
    if (address >= 0x0400 && address <= 0x07FF) {
        txt_memory_write(address, value);
    }
    if (address >= 0xC000 && address <= 0xC07F) {
        memory_write_handler funcptr =  C0xx_memory_write_handlers[address - 0xC000];
        if (funcptr != nullptr) {
             (*funcptr)(address, value);
        } else return;
    }
}
