# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.4/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bazyar/src/gssquared

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bazyar/src/gssquared

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bazyar/src/gssquared/CMakeFiles /Users/bazyar/src/gssquared//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bazyar/src/gssquared/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gs2

# Build rule for target.
gs2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gs2
.PHONY : gs2

# fast build rule for target.
gs2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/build
.PHONY : gs2/fast

bus.o: bus.cpp.o
.PHONY : bus.o

# target to build an object file
bus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/bus.cpp.o
.PHONY : bus.cpp.o

bus.i: bus.cpp.i
.PHONY : bus.i

# target to preprocess a source file
bus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/bus.cpp.i
.PHONY : bus.cpp.i

bus.s: bus.cpp.s
.PHONY : bus.s

# target to generate assembly for a file
bus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/bus.cpp.s
.PHONY : bus.cpp.s

clock.o: clock.cpp.o
.PHONY : clock.o

# target to build an object file
clock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/clock.cpp.o
.PHONY : clock.cpp.o

clock.i: clock.cpp.i
.PHONY : clock.i

# target to preprocess a source file
clock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/clock.cpp.i
.PHONY : clock.cpp.i

clock.s: clock.cpp.s
.PHONY : clock.s

# target to generate assembly for a file
clock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/clock.cpp.s
.PHONY : clock.cpp.s

cpu.o: cpu.cpp.o
.PHONY : cpu.o

# target to build an object file
cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/cpu.cpp.o
.PHONY : cpu.cpp.o

cpu.i: cpu.cpp.i
.PHONY : cpu.i

# target to preprocess a source file
cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/cpu.cpp.i
.PHONY : cpu.cpp.i

cpu.s: cpu.cpp.s
.PHONY : cpu.s

# target to generate assembly for a file
cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/cpu.cpp.s
.PHONY : cpu.cpp.s

debug.o: debug.cpp.o
.PHONY : debug.o

# target to build an object file
debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/debug.cpp.o
.PHONY : debug.cpp.o

debug.i: debug.cpp.i
.PHONY : debug.i

# target to preprocess a source file
debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/debug.cpp.i
.PHONY : debug.cpp.i

debug.s: debug.cpp.s
.PHONY : debug.s

# target to generate assembly for a file
debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/debug.cpp.s
.PHONY : debug.cpp.s

gs2.o: gs2.cpp.o
.PHONY : gs2.o

# target to build an object file
gs2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/gs2.cpp.o
.PHONY : gs2.cpp.o

gs2.i: gs2.cpp.i
.PHONY : gs2.i

# target to preprocess a source file
gs2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/gs2.cpp.i
.PHONY : gs2.cpp.i

gs2.s: gs2.cpp.s
.PHONY : gs2.s

# target to generate assembly for a file
gs2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/gs2.cpp.s
.PHONY : gs2.cpp.s

memory.o: memory.cpp.o
.PHONY : memory.o

# target to build an object file
memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/memory.cpp.o
.PHONY : memory.cpp.o

memory.i: memory.cpp.i
.PHONY : memory.i

# target to preprocess a source file
memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/memory.cpp.i
.PHONY : memory.cpp.i

memory.s: memory.cpp.s
.PHONY : memory.s

# target to generate assembly for a file
memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/memory.cpp.s
.PHONY : memory.cpp.s

opcodes.o: opcodes.cpp.o
.PHONY : opcodes.o

# target to build an object file
opcodes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/opcodes.cpp.o
.PHONY : opcodes.cpp.o

opcodes.i: opcodes.cpp.i
.PHONY : opcodes.i

# target to preprocess a source file
opcodes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/opcodes.cpp.i
.PHONY : opcodes.cpp.i

opcodes.s: opcodes.cpp.s
.PHONY : opcodes.s

# target to generate assembly for a file
opcodes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/opcodes.cpp.s
.PHONY : opcodes.cpp.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gs2.dir/build.make CMakeFiles/gs2.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gs2"
	@echo "... bus.o"
	@echo "... bus.i"
	@echo "... bus.s"
	@echo "... clock.o"
	@echo "... clock.i"
	@echo "... clock.s"
	@echo "... cpu.o"
	@echo "... cpu.i"
	@echo "... cpu.s"
	@echo "... debug.o"
	@echo "... debug.i"
	@echo "... debug.s"
	@echo "... gs2.o"
	@echo "... gs2.i"
	@echo "... gs2.s"
	@echo "... memory.o"
	@echo "... memory.i"
	@echo "... memory.s"
	@echo "... opcodes.o"
	@echo "... opcodes.i"
	@echo "... opcodes.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

