#pragma once

typedef enum device_id {
    DEVICE_ID_END = 0,
    DEVICE_ID_KEYBOARD_IIPLUS,
    DEVICE_ID_KEYBOARD_IIE,
    DEVICE_ID_SPEAKER,
    DEVICE_ID_DISPLAY,
    DEVICE_ID_GAMECONTROLLER,
    DEVICE_ID_LANGUAGE_CARD,
    DEVICE_ID_PRODOS_BLOCK,
    DEVICE_ID_PRODOS_CLOCK,
    DEVICE_ID_DISK_II,
    DEVICE_ID_MEM_EXPANSION,
    DEVICE_ID_THUNDER_CLOCK,
    DEVICE_ID_PD_BLOCK2,
    DEVICE_ID_PARALLEL,
    DEVICE_ID_VIDEX,
    DEVICE_ID_MOCKINGBOARD,
    NUM_DEVICE_IDS
} device_id;
