#pragma once

typedef enum {
    MODULE_DISPLAY = 0,
    MODULE_KEYBOARD,
    MODULE_SPEAKER,
    MODULE_GAMECONTROLLER,
    MODULE_DISKII,
    MODULE_MEMEXP,
    //MODULE_LANGCARD,
    MODULE_THUNDERCLOCK,
    MODULE_PRODOS_CLOCK,
    //MODULE_PD_BLOCK2,
    MODULE_PARALLEL,
    MODULE_VIDEX,
    //MODULE_MB,
    MODULE_ANNUNCIATOR,
    MODULE_IIEMEMORY,
    MODULE_NUM_MODULES
} module_id_t;
